# -*- coding: utf-8 -*-
"""Image embedding Yolo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWNQjV6qYh7qqRacJu9hm8gMda5jLS62
"""

!pip install ultralytics sentence-transformers

import torch
import torch.nn.functional as F
from ultralytics import YOLO
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"

yolo = YOLO("yolov8n.pt")
yolo.model.to(device)
yolo.model.eval()

from google.colab import files
files.upload()

def get_image_embedding(image_path):
    image = Image.open(image_path).convert("RGB")

    results = yolo(image, verbose=False)

    features = results[0].feat            # (1, C, H, W)
    embedding = torch.mean(features, dim=[2, 3])  # Global Avg Pool → (1, C)
    embedding = F.normalize(embedding, dim=1)

    return embedding

import torch
import torch.nn.functional as F
from ultralytics import YOLO
from PIL import Image
import torchvision.transforms as T

device = "cuda" if torch.cuda.is_available() else "cpu"

yolo = YOLO("yolov8n.pt")
backbone = yolo.model.model[:10]   # backbone layers only
backbone.to(device)
backbone.eval()

transform = T.Compose([
    T.Resize((640, 640)),
    T.ToTensor()
])

def get_image_embedding(image_path):
    image = Image.open(image_path).convert("RGB")
    image = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        features = backbone(image)   # (1, C, H, W)

    # Global Average Pooling
    embedding = torch.mean(features, dim=[2, 3])  # (1, C)

    # Normalize
    embedding = F.normalize(embedding, dim=1)

    return embedding

img_emb = get_image_embedding("/content/Tomato.jpg")
print("Image embedding shape:", img_emb.shape)

from sentence_transformers import SentenceTransformer

text_model = SentenceTransformer("all-MiniLM-L6-v2").to(device)

def get_text_embedding(texts):
    emb = text_model.encode(texts, convert_to_tensor=True)
    emb = F.normalize(emb, dim=1)
    return emb

texts = [
    "leaf disease in tomato plant",

]

txt_emb = get_text_embedding(texts)
print(txt_emb.shape)

import torch.nn as nn

image_proj = nn.Linear(256, 256).to(device)
text_proj = nn.Linear(384, 256).to(device)

img_emb_proj = F.normalize(image_proj(img_emb), dim=1)
txt_emb_proj = F.normalize(text_proj(txt_emb), dim=1)

similarity = torch.matmul(img_emb_proj, txt_emb_proj.T)
print("Similarity scores:\n", similarity)
print("Shape:", similarity.shape)