# -*- coding: utf-8 -*-
"""Image embedding Hugging face

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxTWmRFs6NAXhAQxtIjqUciB19ookA-Z
"""

!pip install -q torch torchvision transformers pillow

import torch
from transformers import CLIPProcessor, CLIPModel

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

model_name = "openai/clip-vit-base-patch32"

processor = CLIPProcessor.from_pretrained(model_name)
model = CLIPModel.from_pretrained(model_name).to(device)
model.eval()

from google.colab import files
files.upload()

from google.colab import files
files.upload()

from PIL import Image
import torch

image_paths = ["/content/Tomato.jpg", "/content/Banana.jpg"]
embeddings = []

for path in image_paths:
    image = Image.open(path).convert("RGB")
    inputs = processor(images=image, return_tensors="pt").to(device)

    with torch.no_grad():
        feat = model.get_image_features(**inputs)

    feat = feat / feat.norm(dim=-1, keepdim=True)
    embeddings.append(feat)

image_embeddings = torch.cat(embeddings, dim=0)
print("Image embeddings shape:", image_embeddings.shape)

import torch

texts = [
    "leaf disease in tomato plant",

    "banana leaf disease"
]

# Batch process texts
text_inputs = processor(
    text=texts,
    return_tensors="pt",
    padding=True
).to(device)

with torch.no_grad():
    text_features = model.get_text_features(**text_inputs)

# Normalize for cosine similarity
text_embeddings = text_features / text_features.norm(dim=-1, keepdim=True)

print("Text embeddings shape:", text_embeddings.shape)

similarity = torch.matmul(image_embedding, text_embedding.T)
print("Similarity score:", similarity.item())

similarity = torch.matmul(image_embedding, text_embeddings.T)
print("Similarity shape:", similarity.shape)
print("Similarity scores:", similarity)